{
   "baseURL": "https://blog.netdata.cloud/",
   "languageCode": "en-us",
   "title": "Netdata Blog",
   "theme": "hello-friend",
   "params": {
      "ReadMore": "more",
   },
   "languages": {
   }
}